#!/bin/bash

set -eo pipefail

usage() {
    printf "usage:\t%s [up|down|logs|status|help]\n" "$0"
    printf "or\t%s COMMAND\n" "$0"
}

run_compose() {
    if ! which docker-compose &>/dev/null; then
        echo "error: you don't have docker-compose." 2>&1
        exit 1
    fi
    exec docker-compose -f docker-compose/dev.yml "$@"
}


if [ "$?" -lt 1 ]; then
    usage
    exit 1
fi

case "$1" in
    "up")
        run_compose up -d
        ;;
    "down")
        run_compose down
        ;;
    "logs")
        run_compose logs -f
        ;;
    "status")
        run_compose ps
        ;;
    "help")
        usage
        ;;
    *)
        run_compose run api "$@"
        ;;
esac
