# Generated by Django 2.0.2 on 2018-02-15 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_url', models.CharField(max_length=1024)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=1024)),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Position')),
                ('related_topics', models.ManyToManyField(blank=True, related_name='_topic_related_topics_+', to='api.Topic')),
                ('summary_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='resources',
            field=models.ManyToManyField(to='api.Resource'),
        ),
    ]
